### PR TITLE
README.md: fix typo

### PR DESCRIPTION
**Pull request by jorrit**

### CODE REVIEW

**Comment by SimonFrings** [comment]
@jorrit Good catch :+1:

The HHVM build is currently failing in all ReactPHP components because Composer 2.3 does not longer support legacy PHP or legacy HHVM. @clue and I discussed the whole topic and came up with a fix: reactphp/socket#289.

I will fill in PRs that fix the same issue across the other components (and in here). After that I we will come back to this ticket, shouldn't take long.

**Review by WyriHaximus — APPROVED** [review]

**Comment by WyriHaximus** [comment]
@SimonFrings Honestly, this is a non-code change. The failing pipeline is irrelevant and we have no reason to wait for it to be fixed and can just merge this in as is.

**Comment by SimonFrings** [comment]
@WyriHaximus Fine by me :+1: 
Also filled in the other PR in #450.

**Review by SimonFrings — APPROVED** [review]

**Review by clue — APPROVED** [review]
@jorrit Thanks for the quick fix, keep it coming! :shipit:

**Pull request merged**
