### PR TITLE
Added multipart support

### PR DESCRIPTION
**Pull request by arunpoudel**
Added multipart support, will work on test cases after we have discussed the implementation.

### CODE REVIEW

**Comment by cboden** [comment]
As stated in [this comment](https://github.com/reactphp/http/pull/13#discussion_r22383499) I don't feel multi-part handling should be tightly coupled to the filesystem, I think providing indirection to the developer to pipe to the filesystem or another socket would be better. 

That is just my thought I'm open to opinions.

**Comment by arunpoudel** [comment]
Yes that would make sense. I would suggest having both header and body as a stream using stream_context_create().

**Comment by WyriHaximus** [comment]
I'm with @cboden on this. Using streams empowers the developer to handle the uploaded file in a desired way for the project.

**Comment by clue** [comment]
Thanks for filing this PR @arunpoude and I really appreciate your effortl :+1:
 
I think this addresses a real issue, but I'd rather address parsing via #105. That ticket also mentions quite a few pitfalls that I don't see being addressed in this PR.

This is kind of an old PR and it contains plenty of merge conflicts now. Unfortunately, this hasn't been updated in years, so I'll close this due to a lack of feedback. If you think this is still worth addressing, please update this PR or file a new one and we can reconsider this :+1:

**Pull request closed without merging**
