### PR TITLE
Support json content in RequestParsers class

### PR DESCRIPTION
**Pull request by Abdulrazak-Alkl**
This PR to Support new HTTP content-type "application/json".
Currently body property in request object will contains a JSON object decoded from incoming JSON string.

### CODE REVIEW

**Comment by ephrin** [comment]
-1 I believe mixing in framework like "helpers" to server things is not a good idea.

**Comment by marcj** [comment]
+1, this library's purpose is to marshal data from tcp to PHP objects. When a client sends a file, it converts it to a FileInfo object. When urlencoded, it converts it to php array. So, when the client sends json, this library should also convert this into a php array. The only conclusion you could make. Actually I as a React\Request object consumer don't care which content-type the client used. I want to sent data, not in a raw format.

**Comment by staabm** [comment]
Not sure if FileInfo is appropriate because it might require to load a file into memory which wouldnt work for big/huge files. Something streamable would be good.

**Comment by clue** [comment]
Afaict this has been filed to build a new feature on top of the previously broken master branch. Now that #59 is in, is this still relevant?

**Comment by clue** [comment]
Thanks for filing this PR, I can assure you we're working hard on this :+1:

This PR currently targets an unstable development feature that is no longer part of the master branch, so I've just filed #105 to keep track of the underlying feature request here. Please bear with us, we'll keep this ticket updated :+1:

**Pull request closed without merging**
