### PR TITLE
Removed testing against HHVM nightly

### PR DESCRIPTION
**Pull request by WyriHaximus**
HHVM is broken on travis for a while now.

### CODE REVIEW

**Comment by WyriHaximus** [comment]
@clue @jsor 👍 or 👎 ?

**Comment by jsor** [comment]
👍

**Comment by clue** [comment]
Perhaps I'm missing something, but what is the point in adding PHP 7.1 here? Afaict there are no BC breaks and nothing we take advantage of in particular, so should we really keep adding new versions to our ever growing test matrix? Also, what about our other components?

:+1: on dropping unsupported/broken hhvm-nightly builds
+-0 on adding PHP 7.1 support

**Comment by WyriHaximus** [comment]
Right the addition of 7.1 is a force of habit of always testing against all supported versions. I'm +-0 on it to be honest so if anyone insists on not testing against it that is fine by me since we also test against 7.0.

**Pull request merged**
