### PR TITLE
Add new HeaderBag (modeled after Symfony) to support case-insensitive header matching.

### PR DESCRIPTION
**Pull request by pwhelan**
Used a new HeaderBag class to support case-insensitive header name matches. This fixes a bug where ab (Apache Benchmark) simply hangs.

### CODE REVIEW

**Comment by clue** [comment]
> support case-insensitive header name matches

Thanks for your effor @pwhelan! I agree that this a bug that needs fixing :+1: 

However, the current implementation contains a BC break and I see little we could do about this on this level. As an alternative, I would vote for waiting for #41 to remove most (all?) of the assumptions on headers.

FWIW: Proper header parsing will probably be resolved once we look into PSR-7 support (#28).

**Comment by clue** [comment]
Afaict this has been filed to fix the previously broken master branch. Now that #59 is in, is this still relevant?

**Comment by pwhelan** [comment]
> Afaict this has been filed to fix the previously broken master branch. Now that #59 is in, is this still relevant?

I'll have to test that to be sure. This bug was kept open pending the merge of #41 (at least on my end). 

I'll test this soon to be sure. This was meant primarily to fix problems with ab (Apache Benchmark) and other http clients (curl, possibly jmeter as well) which use 'Content-length' instead of 'Content-Length'. This happens enough in the wild that it has to be supported.

If #59 does fix this then it can be closed.

**Comment by clue** [comment]
Thanks for filing this PR, I can assure you we're working hard on this :+1:

This PR currently targets an unstable development feature that is no longer part of the master branch, so I've just filed #105 to keep track of the underlying feature request here. Please bear with us, we'll keep this ticket updated :+1:

See also #51, which I'm currently looking into :+1:

**Pull request closed without merging**
