### PR TITLE
Minor documentation fix for broken anchor link

### PR DESCRIPTION
**Pull request by fritz-gerneth**
Just some random broken link :)

### CODE REVIEW

**Review by WyriHaximus — APPROVED** [review]

**Review by clue — COMMENTED** [review]
@fritz-gerneth Thanks for looking into this!

This repo is still on travis-co.org instead of .com. We will likely migrate to GitHub actions soon, so I don't think it makes sense to get this change in as-is.

The other documentation change LGTM. Perhaps you can amend your changes to only fix this link? :+1:

**Comment by fritz-gerneth** [comment]
Travis link is reverted now.

**Comment by clue** [comment]
@fritz-gerneth Thanks for the update! May I ask you to squash your changes into one commit?

```bash
$ GIT_SEQUENCE_EDITOR="sed -i -re 's/^pick (d13976a)/fixup \1/'" git rebase -i HEAD~2
```

**Comment by fritz-gerneth** [comment]
It won't alllow me to rewrite published commits. Not sure if GitHub can squash merges. We can use [this ](https://github.com/funct/http/tree/broken-anchor-link) branch instead if it suits better.

**Comment by clue** [comment]
@fritz-gerneth This should be possible via normal git operations with a rebase (see above) and a force push.

As a suggestion, we can also schedule a short 15-20 minute call on Zoom. That should be enough to get your problem out of the way so we can make further progress. We live and love open-source, so we offer such calls from time to time to help out where possible. Just drop me a quick mail if you're interested.

**Comment by fritz-gerneth** [comment]
Appreciate the offer apologies for the long delay here. This is now corrected & rebased.

**Review by clue — APPROVED** [review]
@fritz-gerneth Thanks for the update, changes LGTM! :+1:

**Review by jsor — APPROVED** [review]

**Pull request merged**
