### PR TITLE
Added accessor for $conn (ConnectionInterface) in the response object

### PR DESCRIPTION
**Pull request by sasquatch-mc**
I found useful to have such getter method for the connection if for example you need the connected client's remote address.

### CODE REVIEW

**Comment by WyriHaximus** [comment]
LGTM :+1:

**Comment by clue** [comment]
> connected client's remote address

:+1:  on getting accessing to this information!

:-1: on exposing the underlying connection stream. IMO this breaks our abstraction layers and leaks unrelated information (and responsibility).

Unless we can come up with a use case that actually relies on the underlying stream I'd rather look into how we should expose the client address (PSR-7 anybody?).

How do other http server libs expose this information?

**Comment by clue** [comment]
What is the status on this PR?

As of v0.4.0 (0c3cae87a0fbc84531de81d5e8943a273eeffc5f) the `Request` object has a public `remoteAddress` property.

**Comment by clue** [comment]
I believe this has been resolved as per the above comment, so I'm closing this for now. If you think this is still an issue, please come back with more details and will happily look into this :+1:

**Pull request closed without merging**
