### PR TITLE
Forward compatibility with Stream v1.0 and v0.7

### PR DESCRIPTION
**Pull request by clue**
Builds on top of #183

### CODE REVIEW

**Comment by clue** [comment]
Updated to simplify buffering tests by using new react/promise-stream release :shipit:

**Comment by WyriHaximus** [comment]
@clue changes look good, but any idea why the `lowest` builds are failing?

**Comment by clue** [comment]
@WyriHaximus Updated the first commit to target at least [react/stream v0.4.6](https://github.com/reactphp/stream/releases/tag/v0.4.6) which contains a bugfix for the `ThroughStream` that is now used in the test suite :shipit:

**Comment by WyriHaximus** [comment]
Cheers 👍

**Pull request merged**
