### PR TITLE
Support \Throwable when setting previous exception from server callback

### PR DESCRIPTION
**Pull request by jsor**
Followup for #152

### CODE REVIEW

**Comment by andig** [comment]
Won't `Throwable` kill php prior to 7?

**Comment by jsor** [comment]
@clue What do you mean exactly? This just sets the `$previous` argument for the emitted `\RuntimeException`.
@andig Not sure what you mean. Can you elaborate?

**Comment by maciejmrozinski** [comment]
@jsor I think, what @andig had in mind, was that `Throwable` is not defined in PHP < 7.0 and how such situation will be handled - fatal or just false statement.

@andig For PHP < 7.0 it will just evaluate to false.

**Comment by andig** [comment]
@maciejmrozinski Indeed, verified using l3v4.

**Comment by jsor** [comment]
@maciejmrozinski Thanks for the clarification! Yes, with PHP5 `\Throwable` just isn't declared and the instanceof check will evaluate to false.

**Comment by jsor** [comment]
The question is rather if we should completely switch over to use `\Throwable` as type hints in the documentations across our components?

**Comment by Yoshi2889** [comment]
Hit this wall too, setting this up would mean stuff like `\Error` would get passed to the previous exception parameter too, and therefore generic PHP errors can be found.

**Comment by clue** [comment]
I agree that we should get this in, but we should make sure this is mentioned in the README (which only mentions `Exception` currently). Ultimately we may want to switch to `Throwable` only, but that would involve dropping PHP < 7.0, which I'd rather discuss separately (https://github.com/reactphp/react/issues/374) :+1:

**Comment by jsor** [comment]
> I agree that we should get this in, but we should make sure this is mentioned in the README (which only mentions Exception currently).

@clue Yes, and that is correct because the server will **always** emit a `\RuntimeException`. This patch only handles the [`$previous` argument for this  exception](https://github.com/reactphp/http/pull/155/files#diff-c611f5024b5b13f69f779505d1c6735eR268).

**Comment by clue** [comment]
>  […] the server will always emit a \RuntimeException. This patch only handles the $previous argument for this exception.

I think this should be mentioned in the README :+1: 

In particular, it currently says (emphasis mine):

> The server will also emit an error event if you return an invalid type in the callback function or have a **unhandled Exception**. If your callback function **throws an exception**, the Server will emit a RuntimeException and **add the thrown exception as previous**:

**Comment by jsor** [comment]
To properly support `Throwables`, [`react/promise: ^2.3`](https://github.com/reactphp/promise/releases/tag/v2.3.0) is required as that version introduced support for it.

Should we bump the version in composer.json or add a note to the readme?

**Comment by WyriHaximus** [comment]
@jsor bumping sounds like a good idea to me :+1:

**Comment by WyriHaximus** [comment]
🎉

**Pull request merged**
