### PR TITLE
Increase the message parser speed with pecl

### PR DESCRIPTION
**Pull request by ichiriac**
Hi,

This pull-request is an optimization of the message parser : 
- using the pecl version of parser if available
- avoid creating a new parser at each run because, after reviewing the code of guzzle message parser, no 1 time $this is used (so no memory leaks possible)

I've made some benchmarks, I have 10% of increase at req/sec on a HelloWorld benchmark.

### CODE REVIEW

**Comment by cboden** [comment]
+1 on the faster parser
-1 on the static variable

**Comment by WyriHaximus** [comment]
LGTM :+1: although the static variable smells imho. Any particular reason you went for that?

**Comment by clue** [comment]
I agree, +1 on using the faster parser if it's available, -1 on evaluating it for each request.

The parser appears to be stateless, so afaict there's never been a point in creating a new one on each request in the first place. How about moving this to the ctor and passing one via DI? Your logic can then be applied as the default behavior if no parser has been given explicitly.

**Comment by HonzaMac** [comment]
@ichiriac is it possible to change that `self::` to `$this->` ?

**Comment by cboden** [comment]
Given the underlying HTTP parser has been swapped out with RingCentral I don't think this is applicable any longer. Thank you for your contribution, my apologies we couldn't fit it into the codebase.

**Pull request closed without merging**
