### PR TITLE
Emit error event for invalid requests (instead of crashing)

### PR DESCRIPTION
**Pull request by clue**

### CODE REVIEW

**Comment by clue** [comment]
Turns out this is a duplicate of #66, I guess I should probably have checked my mails first :)

**Comment by WyriHaximus** [comment]
Yeah no problem, was watching the stream and decided to fix it right away :+1: . Thanks for putting in this PR non the less :+1:

**Comment by WyriHaximus** [comment]
@clue The fixes in both are nearly identical, the only main difference are not removing listeners in your PR vs removing listeners in mine.  Lets pick one? :smile: Personally I'm in favor of mine because it stops listening, catches more exceptions (shouldn't matter though). How ever yours also emits `$this` with the error, could add that to mine. What do you think?

**Comment by clue** [comment]
I agree, yours has been there first, which makes mine a duplicated :-)

Now let's look into getting #65 instead :shipit:

**Pull request closed without merging**
